task:
  name: macOS
  osx_instance:
    image: mojave-xcode-11
  download_dependencies_script: make cache
  brew_update_script: brew update
  install_carthage_script: brew install carthage
  xcode_version_script: xcodebuild -version
  test_macos_script: make test-macos

task:
  name: iOS
  osx_instance:
    image: mojave-xcode-11
  download_dependencies_script: make cache
  brew_update_script: brew update
  install_carthage_script: brew install carthage
  xcode_version_script: xcodebuild -version
  xcode_show_destinations_script: make show-destinations
  test_ios_script: make test-ios

task:
  name: Linux
  container:
    image: swift:latest
  build_script: swift build

task:
  name: macOS SPM
  osx_instance:
    image: mojave-xcode-10.3
  build_script: swift build
