language: objective-c
osx_image: xcode8.1
before_script:
- brew update
- brew install carthage
- carthage version
- gem install xcpretty
- security create-keychain -p travis ios-build.keychain
- security default-keychain -s ios-build.keychain
- security unlock-keychain -p travis ios-build.keychain
- security set-keychain-settings -t 3600 -l ~/Library/Keychains/ios-build.keychain
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- security import ./scripts/certs/dist.cer -k ~/Library/Keychains/ios-build.keychain
  -T /usr/bin/codesign
- security import ./scripts/certs/dist.p12 -k ~/Library/Keychains/ios-build.keychain
  -P $KEY_PASSWORD -T /usr/bin/codesign
- date
script:
- carthage checkout
- travis_retry make test
after_script:
- date
- security delete-keychain ios-build.keychain
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: a8tGuJggBK0qyY9oOEp1Y0zeA0zTu8safu34t7RNE3IPRj116rIKf1e/y9FxYRKu5BWmc62K8KTM0mPwsPgef7fizleHqPEE6brUJ3hiysNh92gDLHjqHKq6XK3WuMCDTKmgtbdJQbIBGGfAq+xkLCrhDMkm++88p1vmNbR2k2flpvHIV8opnIBsny62pMmgt8prEtsAT5NCVelVSlyRkwiVqvWk+zR9+Wi4jRWr24cv7WBjKgGO/LcxYi/zQEaLK3Ya38TFX29Ky6thNySHpikqDOiAzUwk6byZ05z8GiQ+TJ4P1+nzpKj4ZFg75v0A1wGkssOznuzZeRjl2GOyfqSsdoFflem9mLF97W3h0jUmzI6X3rP050gYgnjklacT9yk36IfsHdr1d6VTsU1Tx/z4yg8fDXTdY5SFIGZ/GReBwmvyVpbaR3yGbyKkaVSRSU8ixW1zq7BGZGSnMj+doKT5231wf1Be8M5PBtorBh/arOynZPOhpxzAFsoRKL9GRSgxuQIzFOdE/u56PfxjDhTCzuJu0F0ynlR6fIX2PWdrhejfvDpWx/dJWr9x85BKL3rGO8JaXAXlbils+CoEY/Pyfs2UoAaV8TGJR12FJbyl70VZ1hq/qimbFJ6z8TF435LrAA1/VO7qkDLgIJeqPnVnmKiPP3qNHBCNZA1vgzY=
  - secure: IW9jgSdH76Rgp4Hf45+7saqTYslau7K/KgnRtizVZnQwI31b/dMrimMuQj3m6R80ymetz1ZhLk5dX83g+Y5A4XAJjspk2vaAE3ZIZUo6mqdtkRxzxkomN5HZEzEAj8SdjQ4GZxLHX2skATP78SWKJrr7vBbfigPm/Pp8gt4AfKzmfVnBGiN8niU6q/qSUNq67j+F0J/bB2hhOQjIO4mbHRAPW+AygGV9/o+25k+fL4yXWpsDoKzMFTsWHp9H9NkevGFXwK7crGX/Bgo8QESOvVZT4JEnHapEKnT8tAkT3wUCNKiPp60lAo9r/eggASU2a8Oq03wSZMv1F88ORzBVKQfSlNHcV0XOylYL2JZqtzznPmTRx2biHncB8xSg/DBh4MtUKuuProsq+/KIy067pITYCudEqjqL7YjaLlDEUl+YiahOY4DJ391GaCkCklUbHv1TW3vdDpBSvjtC4Ny7anNqK5Mo/cwscPGBTgkQkFyzRf48WLf79wH1sonIVQXv5wKxJAAn08K48dUfhK7yuePjHKmXsKpSjJJbPPlcAEvOknGQnG9OQ6MWb2A/Wk01ki29CENRFbVZCWG2CcM8bPTLGxz07Dp6VH3nxQoQHgsH/J4j1hWfnL1DGacFrDzC/SFhB78v65FxheV5ZOEx+Es/eSRiPEdX8gdjZnqOb3Y=
  - secure: GB7YLYmEQ3thnfa4tJ2/O8d7bCYTnyqCI3OOe/dLrRJysZQLXTrJYiibabKcUi8FRMkcrCU/BeNbzZwfSPwjwUGW64ESaH3fKpoGbCZ86jCgsyTXd6s+u3jMGiWCaAco8GUck64Fqfq646xKyaG+ApebK3MybwKySSYMmue1rst+2H/c0zqxDM75ebQALfgUSfrhD8nneGhMyrXUyHN/nf4ZNUV6iGXx9ksUICLHwSDICi8VY3jRvOnCUdVobBwZ7gsAy+18KQR/tyZt3LSVtKFwgdJLNRwaEwquCGYNoqBT5Nb5Yokh7Ejq7szm3o5fWb1C5mxUc1fnefIuaKQtMKynuCefy/cNMAatHGWTnJbQrpmsMkzv7DkxL0uFjtd4eN9U9qk1GdMRWW1fmP4T0pSThDRqfRMD0B+dfsguD+Q9gqJgHOyTdO/2Zjb6JNs5VDh2vE44uvqYuzWA6ki39MfLNgOnoLZjZmml9lSuN41dczrg8R8fH65Ozwb3uNbrq6yeBKa3k+5ybtrthhDn23jcr0PyseM9Hhne7Df6olrq2ASwWgFjYKsgLHvBA5J+b+uWQiazAbEjyuVmr6uRLsCimdNKvIwvBgvSJdwaiQXrrBT9VPcwb0YODrJBI7ZU4/zzlJb/hYJnCDzkAB2Cu7F4y5/5YyZkx09LmxT2B4o=
  - secure: shvEdwYn1lZnBjioXTxLb6dSAa2KDNvhFyPo4r0XDfAGKIBBQFvOUgDrQT+aX/6KxX3sXBEuzUNz3/9DBJqmsW7+JBpaQQGSCI9A8pIUIeXyrgJzvhPPRH+hD7IGvbsqQkQTsIqyAvU23fI8DmriMnsvQpnEPXUCH5OXTBoHfVHxCiGjqNc86uXBzHANtHfIfSRgcgZX+VgjavoIFMHHhFFRFR1junC3XkKRfaheEiAqt133OX1O5zzpNFWI31ZLZxbXUVltJ62PVfJLI0ZfwYVDyKdCsUtbRMv2+nCg/oZtPIY70PmK+mho19sClwYG7t8MHWW3lYXaC+/ijYsBb0c47tpXbTNw2Dr89I5oqRu3HrGBGwBK7/0o+2nfHwllm+8IoMp0O0fjOe6giSjgX7cd0nnUqyNxr9jgSRCd8t0eW/IMlK3yAbpnEJNe7Zd3jmp0v5f0JnsZheoSWyXv6lNQGyXprCZ9L8EASGy3HDoFrAB0CC0VvJxzBcrJCPRRpi5DlPQIAjo8SDlSipSGHtZHSEGqsRaKH6vpqgkbDcGg59A6QYggA/aDGnpqxjFgj6JpWizgB6T+4tzWDcIb5chi3eDU3Hav2XUVFNMjBLf5nPx5VqOQDSecgxVZMcCkQ4lMqcBiYhhwOe2b6eTNKXZGLnKflWNB5y1KVzptO+o=
